settings:
  title: 'Status | Psomium'
  url: 'https://status-page.eidam.dev'
  logo: logo-192x192.png
  daysInHistogram: 60
  collectResponseTimes: true

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)'

monitors:
  - id: https://psomium.com/Home/
    name: Home
    url: 'https://psomium.com/Home/'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: true
    
  - id: https://psomium.com/Shop/
    name: Shop
    url: 'https://psomium.com/Shop/'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: true
    
  - id: https://psomium.com/Product/
    name: Product
    url: 'https://psomium.com/Product/'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: false
    
  - id: https://psomium.com/Product/Item/KI0VZNT7/Connect
    name: API
    url: 'https://psomium.com/Product/Item/KI0VZNT7/Connect?Test=true'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: false
